<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
public function run(): void
    {
        $municipios = [
            ['estado' => 'Amazonas', 'nombre' => 'Alto Orinoco'], ['estado' => 'Amazonas', 'nombre' => 'Atabapo'], ['estado' => 'Amazonas', 'nombre' => 'Atures'], ['estado' => 'Amazonas', 'nombre' => 'Autana'], ['estado' => 'Amazonas', 'nombre' => 'Maroa'], ['estado' => 'Amazonas', 'nombre' => 'Río Negro'], ['estado' => 'Amazonas', 'nombre' => 'Ventuari'],
            ['estado' => 'Anzoátegui', 'nombre' => 'Anaco'], ['estado' => 'Anzoátegui', 'nombre' => 'Aragua'], ['estado' => 'Anzoátegui', 'nombre' => 'Diego Bautista Urbaneja'], ['estado' => 'Anzoátegui', 'nombre' => 'Fernando de Peñalver'], ['estado' => 'Anzoátegui', 'nombre' => 'Francisco del Carmen Carvajal'], ['estado' => 'Anzoátegui', 'nombre' => 'Francisco de Miranda'], ['estado' => 'Anzoátegui', 'nombre' => 'Guanta'], ['estado' => 'Anzoátegui', 'nombre' => 'Independencia'], ['estado' => 'Anzoátegui', 'nombre' => 'José Gregorio Monagas'], ['estado' => 'Anzoátegui', 'nombre' => 'Juan Antonio Sotillo'], ['estado' => 'Anzoátegui', 'nombre' => 'Juan Manuel Cajigal'], ['estado' => 'Anzoátegui', 'nombre' => 'Libertad'], ['estado' => 'Anzoátegui', 'nombre' => 'Manuel Ezequiel Bruzual'], ['estado' => 'Anzoátegui', 'nombre' => 'Pedro María Freites'], ['estado' => 'Anzoátegui', 'nombre' => 'Píritu'], ['estado' => 'Anzoátegui', 'nombre' => 'San José de Guanipa'], ['estado' => 'Anzoátegui', 'nombre' => 'San Juan de Capistrano'], ['estado' => 'Anzoátegui', 'nombre' => 'Santa Ana'], ['estado' => 'Anzoátegui', 'nombre' => 'Simón Bolívar'], ['estado' => 'Anzoátegui', 'nombre' => 'Simón Rodríguez'], ['estado' => 'Anzoátegui', 'nombre' => 'Sir Arthur McGregor'],
            ['estado' => 'Apure', 'nombre' => 'Achaguas'], ['estado' => 'Apure', 'nombre' => 'Biruaca'], ['estado' => 'Apure', 'nombre' => 'Muñoz'], ['estado' => 'Apure', 'nombre' => 'Páez'], ['estado' => 'Apure', 'nombre' => 'Pedro Camejo'], ['estado' => 'Apure', 'nombre' => 'Rómulo Gallegos'], ['estado' => 'Apure', 'nombre' => 'San Fernando'],
            ['estado' => 'Aragua', 'nombre' => 'Bolívar'], ['estado' => 'Aragua', 'nombre' => 'Camatagua'], ['estado' => 'Aragua', 'nombre' => 'Francisco Linares Alcántara'], ['estado' => 'Aragua', 'nombre' => 'Girardot'], ['estado' => 'Aragua', 'nombre' => 'José Ángel Lamas'], ['estado' => 'Aragua', 'nombre' => 'José Félix Ribas'], ['estado' => 'Aragua', 'nombre' => 'José Rafael Revenga'], ['estado' => 'Aragua', 'nombre' => 'Libertador'], ['estado' => 'Aragua', 'nombre' => 'Mario Briceño Iragorry'], ['estado' => 'Aragua', 'nombre' => 'Ocumare de la Costa de Oro'], ['estado' => 'Aragua', 'nombre' => 'San Casimiro'], ['estado' => 'Aragua', 'nombre' => 'San Sebastián'], ['estado' => 'Aragua', 'nombre' => 'Santiago Mariño'], ['estado' => 'Aragua', 'nombre' => 'Santos Michelena'], ['estado' => 'Aragua', 'nombre' => 'Sucre'], ['estado' => 'Aragua', 'nombre' => 'Tovar'], ['estado' => 'Aragua', 'nombre' => 'Urdaneta'], ['estado' => 'Aragua', 'nombre' => 'Zamora'],
            ['estado' => 'Barinas', 'nombre' => 'Alberto Arvelo Torrealba'], ['estado' => 'Barinas', 'nombre' => 'Andrés Eloy Blanco'], ['estado' => 'Barinas', 'nombre' => 'Antonio José de Sucre'], ['estado' => 'Barinas', 'nombre' => 'Arismendi'], ['estado' => 'Barinas', 'nombre' => 'Barinas'], ['estado' => 'Barinas', 'nombre' => 'Bolívar'], ['estado' => 'Barinas', 'nombre' => 'Cruz Paredes'], ['estado' => 'Barinas', 'nombre' => 'Ezequiel Zamora'], ['estado' => 'Barinas', 'nombre' => 'Obispos'], ['estado' => 'Barinas', 'nombre' => 'Pedraza'], ['estado' => 'Barinas', 'nombre' => 'Rojas'], ['estado' => 'Barinas', 'nombre' => 'Sosa'],
            ['estado' => 'Bolívar', 'nombre' => 'Angostura (Raúl Leoni)'], ['estado' => 'Bolívar', 'nombre' => 'Caroní'], ['estado' => 'Bolívar', 'nombre' => 'Cedeño'], ['estado' => 'Bolívar', 'nombre' => 'El Callao'], ['estado' => 'Bolívar', 'nombre' => 'Gran Sabana'], ['estado' => 'Bolívar', 'nombre' => 'Heres'], ['estado' => 'Bolívar', 'nombre' => 'Padre Pedro Chien'], ['estado' => 'Bolívar', 'nombre' => 'Piar'], ['estado' => 'Bolívar', 'nombre' => 'Roscio'], ['estado' => 'Bolívar', 'nombre' => 'Sifontes'], ['estado' => 'Bolívar', 'nombre' => 'Sucre'],
            ['estado' => 'Carabobo', 'nombre' => 'Bejuma'], ['estado' => 'Carabobo', 'nombre' => 'Carlos Arvelo'], ['estado' => 'Carabobo', 'nombre' => 'Diego Ibarra'], ['estado' => 'Carabobo', 'nombre' => 'Guacara'], ['estado' => 'Carabobo', 'nombre' => 'Juan José Mora'], ['estado' => 'Carabobo', 'nombre' => 'Libertador'], ['estado' => 'Carabobo', 'nombre' => 'Los Guayos'], ['estado' => 'Carabobo', 'nombre' => 'Miranda'], ['estado' => 'Carabobo', 'nombre' => 'Montalbán'], ['estado' => 'Carabobo', 'nombre' => 'Naguanagua'], ['estado' => 'Carabobo', 'nombre' => 'Puerto Cabello'], ['estado' => 'Carabobo', 'nombre' => 'San Diego'], ['estado' => 'Carabobo', 'nombre' => 'San Joaquín'], ['estado' => 'Carabobo', 'nombre' => 'Valencia'],
            ['estado' => 'Cojedes', 'nombre' => 'Anzoátegui'], ['estado' => 'Cojedes', 'nombre' => 'Ezequiel Zamora'], ['estado' => 'Cojedes', 'nombre' => 'Girardot'], ['estado' => 'Cojedes', 'nombre' => 'Lima Blanco'], ['estado' => 'Cojedes', 'nombre' => 'Pao de San Juan Bautista'], ['estado' => 'Cojedes', 'nombre' => 'Ricaurte'], ['estado' => 'Cojedes', 'nombre' => 'Rómulo Gallegos'], ['estado' => 'Cojedes', 'nombre' => 'Tinaco'], ['estado' => 'Cojedes', 'nombre' => 'Tinaquillo'],
            ['estado' => 'Delta Amacuro', 'nombre' => 'Antonio Díaz'], ['estado' => 'Delta Amacuro', 'nombre' => 'Casacoima'], ['estado' => 'Delta Amacuro', 'nombre' => 'Pedernales'], ['estado' => 'Delta Amacuro', 'nombre' => 'Tucupita'],
            ['estado' => 'Distrito Capital', 'nombre' => 'Libertador'],
            ['estado' => 'Falcón', 'nombre' => 'Acosta'], ['estado' => 'Falcón', 'nombre' => 'Bolívar'], ['estado' => 'Falcón', 'nombre' => 'Buchivacoa'], ['estado' => 'Falcón', 'nombre' => 'Cacique Manaure'], ['estado' => 'Falcón', 'nombre' => 'Carirubana'], ['estado' => 'Falcón', 'nombre' => 'Colina'], ['estado' => 'Falcón', 'nombre' => 'Dabajuro'], ['estado' => 'Falcón', 'nombre' => 'Democracia'], ['estado' => 'Falcón', 'nombre' => 'Falcón'], ['estado' => 'Falcón', 'nombre' => 'Federación'], ['estado' => 'Falcón', 'nombre' => 'Jacura'], ['estado' => 'Falcón', 'nombre' => 'Los Taques'], ['estado' => 'Falcón', 'nombre' => 'Mauroa'], ['estado' => 'Falcón', 'nombre' => 'Miranda'], ['estado' => 'Falcón', 'nombre' => 'Monseñor Iturriza'], ['estado' => 'Falcón', 'nombre' => 'Palmasola'], ['estado' => 'Falcón', 'nombre' => 'Petit'], ['estado' => 'Falcón', 'nombre' => 'Píritu'], ['estado' => 'Falcón', 'nombre' => 'San Francisco'], ['estado' => 'Falcón', 'nombre' => 'Silva'], ['estado' => 'Falcón', 'nombre' => 'Sucre'], ['estado' => 'Falcón', 'nombre' => 'Tocópero'], ['estado' => 'Falcón', 'nombre' => 'Unión'], ['estado' => 'Falcón', 'nombre' => 'Urumaco'], ['estado' => 'Falcón', 'nombre' => 'Zamora'],
            ['estado' => 'Guárico', 'nombre' => 'Camaguán'], ['estado' => 'Guárico', 'nombre' => 'Chaguaramas'], ['estado' => 'Guárico', 'nombre' => 'El Socorro'], ['estado' => 'Guárico', 'nombre' => 'Francisco de Miranda'], ['estado' => 'Guárico', 'nombre' => 'José Félix Ribas'], ['estado' => 'Guárico', 'nombre' => 'José Tadeo Monagas'], ['estado' => 'Guárico', 'nombre' => 'Juan Germán Roscio'], ['estado' => 'Guárico', 'nombre' => 'Julián Mellado'], ['estado' => 'Guárico', 'nombre' => 'Las Mercedes'], ['estado' => 'Guárico', 'nombre' => 'Leonardo Infante'], ['estado' => 'Guárico', 'nombre' => 'Pedro Zaraza'], ['estado' => 'Guárico', 'nombre' => 'Ortiz'], ['estado' => 'Guárico', 'nombre' => 'San Gerónimo de Guayabal'], ['estado' => 'Guárico', 'nombre' => 'San José de Guaribe'], ['estado' => 'Guárico', 'nombre' => 'Santa María de Ipire'],
            ['estado' => 'Lara', 'nombre' => 'Andrés Eloy Blanco'], ['estado' => 'Lara', 'nombre' => 'Crespo'], ['estado' => 'Lara', 'nombre' => 'Iribarren'], ['estado' => 'Lara', 'nombre' => 'Jiménez'], ['estado' => 'Lara', 'nombre' => 'Morán'], ['estado' => 'Lara', 'nombre' => 'Palavecino'], ['estado' => 'Lara', 'nombre' => 'Simón Planas'], ['estado' => 'Lara', 'nombre' => 'Torres'], ['estado' => 'Lara', 'nombre' => 'Urdaneta'],
            ['estado' => 'Mérida', 'nombre' => 'Alberto Adriani'], ['estado' => 'Mérida', 'nombre' => 'Andrés Bello'], ['estado' => 'Mérida', 'nombre' => 'Antonio Pinto Salinas'], ['estado' => 'Mérida', 'nombre' => 'Aricagua'], ['estado' => 'Mérida', 'nombre' => 'Arzobispo Chacón'], ['estado' => 'Mérida', 'nombre' => 'Campo Elías'], ['estado' => 'Mérida', 'nombre' => 'Caracciolo Parra Olmedo'], ['estado' => 'Mérida', 'nombre' => 'Cardenal Quintero'], ['estado' => 'Mérida', 'nombre' => 'Guaraque'], ['estado' => 'Mérida', 'nombre' => 'Julio César Salas'], ['estado' => 'Mérida', 'nombre' => 'Justo Briceño'], ['estado' => 'Mérida', 'nombre' => 'Libertador'], ['estado' => 'Mérida', 'nombre' => 'Miranda'], ['estado' => 'Mérida', 'nombre' => 'Obispo Ramos de Lora'], ['estado' => 'Mérida', 'nombre' => 'Padre Noguera'], ['estado' => 'Mérida', 'nombre' => 'Pueblo Llano'], ['estado' => 'Mérida', 'nombre' => 'Rangel'], ['estado' => 'Mérida', 'nombre' => 'Rivas Dávila'], ['estado' => 'Mérida', 'nombre' => 'Santos Marquina'], ['estado' => 'Mérida', 'nombre' => 'Sucre'], ['estado' => 'Mérida', 'nombre' => 'Tovar'], ['estado' => 'Mérida', 'nombre' => 'Tulio Febres Cordero'], ['estado' => 'Mérida', 'nombre' => 'Zea'],
            ['estado' => 'Miranda', 'nombre' => 'Acevedo'], ['estado' => 'Miranda', 'nombre' => 'Andrés Bello'], ['estado' => 'Miranda', 'nombre' => 'Baruta'], ['estado' => 'Miranda', 'nombre' => 'Brión'], ['estado' => 'Miranda', 'nombre' => 'Bruzual'], ['estado' => 'Miranda', 'nombre' => 'Cristóbal Rojas'], ['estado' => 'Miranda', 'nombre' => 'Chacao'], ['estado' => 'Miranda', 'nombre' => 'El Hatillo'], ['estado' => 'Miranda', 'nombre' => 'Guaicaipuro'], ['estado' => 'Miranda', 'nombre' => 'Independencia'], ['estado' => 'Miranda', 'nombre' => 'Lander'], ['estado' => 'Miranda', 'nombre' => 'Los Salias'], ['estado' => 'Miranda', 'nombre' => 'Páez'], ['estado' => 'Miranda', 'nombre' => 'Paz Castillo'], ['estado' => 'Miranda', 'nombre' => 'Pedro Gual'], ['estado' => 'Miranda', 'nombre' => 'Plaza'], ['estado' => 'Miranda', 'nombre' => 'Simón Bolívar'], ['estado' => 'Miranda', 'nombre' => 'Sucre'], ['estado' => 'Miranda', 'nombre' => 'Urdaneta'], ['estado' => 'Miranda', 'nombre' => 'Zamora'],
            ['estado' => 'Monagas', 'nombre' => 'Acosta'], ['estado' => 'Monagas', 'nombre' => 'Aguasay'], ['estado' => 'Monagas', 'nombre' => 'Bolívar'], ['estado' => 'Monagas', 'nombre' => 'Caripe'], ['estado' => 'Monagas', 'nombre' => 'Cedeño'], ['estado' => 'Monagas', 'nombre' => 'Ezequiel Zamora'], ['estado' => 'Monagas', 'nombre' => 'Libertador'], ['estado' => 'Monagas', 'nombre' => 'Maturín'], ['estado' => 'Monagas', 'nombre' => 'Piar'], ['estado' => 'Monagas', 'nombre' => 'Punceres'], ['estado' => 'Monagas', 'nombre' => 'Santa Bárbara'], ['estado' => 'Monagas', 'nombre' => 'Sotillo'], ['estado' => 'Monagas', 'nombre' => 'Uracoa'],
            ['estado' => 'Nueva Esparta', 'nombre' => 'Antolín del Campo'], ['estado' => 'Nueva Esparta', 'nombre' => 'Arismendi'], ['estado' => 'Nueva Esparta', 'nombre' => 'Díaz'], ['estado' => 'Nueva Esparta', 'nombre' => 'García'], ['estado' => 'Nueva Esparta', 'nombre' => 'Gómez'], ['estado' => 'Nueva Esparta', 'nombre' => 'Maneiro'], ['estado' => 'Nueva Esparta', 'nombre' => 'Marcano'], ['estado' => 'Nueva Esparta', 'nombre' => 'Mariño'], ['estado' => 'Nueva Esparta', 'nombre' => 'Península de Macanao'], ['estado' => 'Nueva Esparta', 'nombre' => 'Tubores'], ['estado' => 'Nueva Esparta', 'nombre' => 'Villalba'],
            ['estado' => 'Portuguesa', 'nombre' => 'Agua Blanca'], ['estado' => 'Portuguesa', 'nombre' => 'Araure'], ['estado' => 'Portuguesa', 'nombre' => 'Esteller'], ['estado' => 'Portuguesa', 'nombre' => 'Guanare'], ['estado' => 'Portuguesa', 'nombre' => 'Guanarito'], ['estado' => 'Portuguesa', 'nombre' => 'Monseñor José Vicente de Unda'], ['estado' => 'Portuguesa', 'nombre' => 'Ospino'], ['estado' => 'Portuguesa', 'nombre' => 'Páez'], ['estado' => 'Portuguesa', 'nombre' => 'Papelón'], ['estado' => 'Portuguesa', 'nombre' => 'San Genaro de Boconoíto'], ['estado' => 'Portuguesa', 'nombre' => 'San Rafael de Onoto'], ['estado' => 'Portuguesa', 'nombre' => 'Santa Rosalía'], ['estado' => 'Portuguesa', 'nombre' => 'Sucre'], ['estado' => 'Portuguesa', 'nombre' => 'Turén'],
            ['estado' => 'Sucre', 'nombre' => 'Andrés Eloy Blanco'], ['estado' => 'Sucre', 'nombre' => 'Andrés Mata'], ['estado' => 'Sucre', 'nombre' => 'Arismendi'], ['estado' => 'Sucre', 'nombre' => 'Benítez'], ['estado' => 'Sucre', 'nombre' => 'Bermúdez'], ['estado' => 'Sucre', 'nombre' => 'Bolívar'], ['estado' => 'Sucre', 'nombre' => 'Cajigal'], ['estado' => 'Sucre', 'nombre' => 'Cruz Salmerón Acosta'], ['estado' => 'Sucre', 'nombre' => 'Libertador'], ['estado' => 'Sucre', 'nombre' => 'Mariño'], ['estado' => 'Sucre', 'nombre' => 'Mejía'], ['estado' => 'Sucre', 'nombre' => 'Montes'], ['estado' => 'Sucre', 'nombre' => 'Ribero'], ['estado' => 'Sucre', 'nombre' => 'Sucre'], ['estado' => 'Sucre', 'nombre' => 'Valdez'],
            ['estado' => 'Táchira', 'nombre' => 'Andrés Bello'], ['estado' => 'Táchira', 'nombre' => 'Antonio Rómulo Costa'], ['estado' => 'Táchira', 'nombre' => 'Ayacucho'], ['estado' => 'Táchira', 'nombre' => 'Bolívar'], ['estado' => 'Táchira', 'nombre' => 'Cárdenas'], ['estado' => 'Táchira', 'nombre' => 'Córdoba'], ['estado' => 'Táchira', 'nombre' => 'Fernández Feo'], ['estado' => 'Táchira', 'nombre' => 'Francisco de Miranda'], ['estado' => 'Táchira', 'nombre' => 'García de Hevia'], ['estado' => 'Táchira', 'nombre' => 'Guásimos'], ['estado' => 'Táchira', 'nombre' => 'Independencia'], ['estado' => 'Táchira', 'nombre' => 'Jáuregui'], ['estado' => 'Táchira', 'nombre' => 'José María Vargas'], ['estado' => 'Táchira', 'nombre' => 'Junín'], ['estado' => 'Táchira', 'nombre' => 'Libertad'], ['estado' => 'Táchira', 'nombre' => 'Libertador'], ['estado' => 'Táchira', 'nombre' => 'Lobatera'], ['estado' => 'Táchira', 'nombre' => 'Michelena'], ['estado' => 'Táchira', 'nombre' => 'Panamericano'], ['estado' => 'Táchira', 'nombre' => 'Pedro María Ureña'], ['estado' => 'Táchira', 'nombre' => 'Rafael Urdaneta'], ['estado' => 'Táchira', 'nombre' => 'Samuel Darío Maldonado'], ['estado' => 'Táchira', 'nombre' => 'San Cristóbal'], ['estado' => 'Táchira', 'nombre' => 'San Judas Tadeo'], ['estado' => 'Táchira', 'nombre' => 'Seboruco'], ['estado' => 'Táchira', 'nombre' => 'Simón Rodríguez'], ['estado' => 'Táchira', 'nombre' => 'Sucre'], ['estado' => 'Táchira', 'nombre' => 'Torbes'], ['estado' => 'Táchira', 'nombre' => 'Uribante'],
            ['estado' => 'Trujillo', 'nombre' => 'Andrés Bello'], ['estado' => 'Trujillo', 'nombre' => 'Boconó'], ['estado' => 'Trujillo', 'nombre' => 'Bolívar'], ['estado' => 'Trujillo', 'nombre' => 'Candelaria'], ['estado' => 'Trujillo', 'nombre' => 'Carache'], ['estado' => 'Trujillo', 'nombre' => 'Escuque'], ['estado' => 'Trujillo', 'nombre' => 'José Felipe Márquez Cañizalez'], ['estado' => 'Trujillo', 'nombre' => 'Juan Vicente Campos Elías'], ['estado' => 'Trujillo', 'nombre' => 'La Ceiba'], ['estado' => 'Trujillo', 'nombre' => 'Miranda'], ['estado' => 'Trujillo', 'nombre' => 'Monte Carmelo'], ['estado' => 'Trujillo', 'nombre' => 'Motatán'], ['estado' => 'Trujillo', 'nombre' => 'Pampán'], ['estado' => 'Trujillo', 'nombre' => 'Pampanito'], ['estado' => 'Trujillo', 'nombre' => 'Rafael Rangel'], ['estado' => 'Trujillo', 'nombre' => 'San Rafael de Carvajal'], ['estado' => 'Trujillo', 'nombre' => 'Sucre'], ['estado' => 'Trujillo', 'nombre' => 'Trujillo'], ['estado' => 'Trujillo', 'nombre' => 'Urdaneta'], ['estado' => 'Trujillo', 'nombre' => 'Valera'],
            ['estado' => 'Vargas', 'nombre' => 'Vargas'],
            ['estado' => 'Yaracuy', 'nombre' => 'Arístides Bastidas'], ['estado' => 'Yaracuy', 'nombre' => 'Bolívar'], ['estado' => 'Yaracuy', 'nombre' => 'Bruzual'], ['estado' => 'Yaracuy', 'nombre' => 'Cocorote'], ['estado' => 'Yaracuy', 'nombre' => 'Independencia'], ['estado' => 'Yaracuy', 'nombre' => 'José Antonio Páez'], ['estado' => 'Yaracuy', 'nombre' => 'La Trinidad'], ['estado' => 'Yaracuy', 'nombre' => 'Nirgua'], ['estado' => 'Yaracuy', 'nombre' => 'Peña'], ['estado' => 'Yaracuy', 'nombre' => 'San Felipe'], ['estado' => 'Yaracuy', 'nombre' => 'Sucre'], ['estado' => 'Yaracuy', 'nombre' => 'Urachiche'], ['estado' => 'Yaracuy', 'nombre' => 'Veroes'], ['estado' => 'Yaracuy', 'nombre' => 'Manuel Monge'],
            ['estado' => 'Zulia', 'nombre' => 'Almirante Padilla'], ['estado' => 'Zulia', 'nombre' => 'Baralt'], ['estado' => 'Zulia', 'nombre' => 'Cabimas'], ['estado' => 'Zulia', 'nombre' => 'Catatumbo'], ['estado' => 'Zulia', 'nombre' => 'Colón'], ['estado' => 'Zulia', 'nombre' => 'Francisco Javier Pulgar'], ['estado' => 'Zulia', 'nombre' => 'Jesús Enrique Lossada'], ['estado' => 'Zulia', 'nombre' => 'Jesús María Semprún'], ['estado' => 'Zulia', 'nombre' => 'La Cañada de Urdaneta'], ['estado' => 'Zulia', 'nombre' => 'Lagunillas'], ['estado' => 'Zulia', 'nombre' => 'Machiques de Perijá'], ['estado' => 'Zulia', 'nombre' => 'Mara'], ['estado' => 'Zulia', 'nombre' => 'Maracaibo'], ['estado' => 'Zulia', 'nombre' => 'Miranda'], ['estado' => 'Zulia', 'nombre' => 'Páez'], ['estado' => 'Zulia', 'nombre' => 'Rosario de Perijá'], ['estado' => 'Zulia', 'nombre' => 'San Francisco'], ['estado' => 'Zulia', 'nombre' => 'Santa Rita'], ['estado' => 'Zulia', 'nombre' => 'Simón Bolívar'], ['estado' => 'Zulia', 'nombre' => 'Sucre'], ['estado' => 'Zulia', 'nombre' => 'Valmore Rodríguez']
        ];

        foreach ($municipios as $muni) {
            $estadoId = DB::table('estado_ve')
                ->where('nombre_estado_ve', $muni['estado'])
                ->value('id_estado_ve');

            if ($estadoId) {
                DB::table('municipio')->updateOrInsert(
                    [
                        'nombre_municipio' => $muni['nombre'],
                        'id_estado_ve' => $estadoId,
                        'created_at' => now(),
                        'updated_at' => now()
                    ],
                    [
                        'nombre_municipio' => $muni['nombre'],
                        'id_estado_ve' => $estadoId,
                        'created_at' => now(),
                        'updated_at' => now()
                    ]
                );
            }
        }
    }
}
