Table sucursales {
  id int [pk, increment]
  nombre varchar(100) [not null]
  direccion varchar(255)
  telefono varchar(20)
  activo boolean [default: true]
}

Table Categorias {
  id int [pk, increment]
  nombre varchar(100) [not null]
  descripcion text
}

Table Productos {
  id int [pk, increment]
  codigo varchar(50) [not null, unique]
  nombre varchar(100) [not null]
  descripcion text
  imagen varchar(255)
  precio_compra decimal(10, 2) [not null]
  precio_venta decimal(10, 2) [not null]
  stock_minimo int [default: 0]
  stock_maximo int [default: 0]
  unidad_medida varchar(50) [not null]
  estado boolean [default: true]
  categoria_id int [ref: > Categorias.id]
}

Table Proveedores {
  id int [pk, increment]
  empresa varchar(100) [not null]
  direccion varchar(255)
  nombre varchar(100) [not null]
  telefono varchar(20)
  email varchar(100)
  estado boolean [default: true]
}

Table Lotes {
  id int [pk, increment]
  codigo_lote varchar(50) [not null]
  fecha_entrada date
  fecha_vencimiento date
  cantidad_inicial int [not null]
  cantidad_actual int [not null]
  precio_compra decimal(10, 2) [null]
  estado boolean [default: true]
  producto_id int [ref: > Productos.id]
  proveedor_id int [ref: > Proveedores.id]
}

Table Inventario_Sucursal_Lote {
  id int [pk, increment]
  sucursal_id int [ref: > sucursales.id]
  lote_id int [ref: > Lotes.id]
  cantidad int [not null]
}
